name       : python-rapidfuzz
version    : 2.13.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/r/rapidfuzz/rapidfuzz-2.13.6.tar.gz : 948445a054d9fb30a93597c325d8836232bd68e61443a88779a57702aa35a007
homepage   : https://maxbachmann.github.io/RapidFuzz/
license    : MIT
component  : programming.python
summary    : Rapid fuzzy string matching
description: |
    RapidFuzz is a fast string matching library for Python and C++, which is using the string similarity calculations from FuzzyWuzzy.
builddeps  :
    - pkgconfig(python3)
    - python-scikit-build
    - rapidfuzz-cpp
build      : |
    %python3_setup
install    : |
    %python3_install
